M48
; DRILL file {KiCad 7.0.8} date Sun Jan 21 01:23:18 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-21T01:23:18-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X107.154Y-48.146
X107.154Y-104.446
X173.8Y-48.146
X173.8Y-104.446
T0
M30
