M48
; DRILL file {KiCad 7.0.8} date Sat Dec  2 16:31:01 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-02T16:31:01-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.430
%
G90
G05
T1
X129.65Y-80.0
X142.0Y-66.79
X142.0Y-93.21
X166.7Y-71.11
X166.7Y-88.89
T0
M30
