M48
; DRILL file {KiCad 8.0.2} date 2025-01-25T00:37:43-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-25T00:37:43-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.845
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T1
X140.6Y-130.4
X141.616Y-135.48
X142.632Y-130.4
T2
X125.49Y-146.87
X137.53Y-146.87
T3
X121.5Y-89.5
X143.5Y-89.5
T4
X86.0Y-153.0
M30
