M48
; DRILL file {KiCad 7.0.8} date Sun Jan 21 01:36:31 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-21T01:36:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.845
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T1
X140.6Y-130.4
X141.616Y-135.48
X142.632Y-130.4
T2
X125.49Y-146.87
X137.53Y-146.87
T3
X65.5Y-78.5
X106.5Y-78.5
X143.5Y-78.5
X184.5Y-78.5
T4
X56.0Y-74.0
X56.0Y-153.0
X194.0Y-74.0
X194.0Y-153.0
T0
M30
