M48
; DRILL file {KiCad 7.0.8} date Sun Jan 21 00:43:32 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-21T00:43:32-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X184.425Y-77.05
T2
X135.0Y-72.0
X135.0Y-119.0
X190.0Y-72.0
X190.0Y-119.0
T0
M30
