M48
; DRILL file {KiCad 7.0.8} date Sat Dec  2 17:36:29 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-02T17:36:29-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X195.219Y-101.33
X196.235Y-106.41
X197.251Y-101.33
T2
X156.225Y-81.0
X157.7Y-113.6
T3
X155.0Y-75.0
X196.0Y-112.0
T0
M30
