M48
; DRILL file {KiCad 7.0.8} date Sun Jan 21 00:57:13 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-21T00:57:13-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X149.92Y-111.484
X149.92Y-113.516
X155.0Y-112.5
T2
X136.0Y-133.0
X160.0Y-133.0
T0
M30
