M48
; DRILL file {KiCad 7.0.8} date Sat Dec  2 16:25:19 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-02T16:25:19-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X152.5Y-113.4
T2
X141.0Y-109.0
X141.0Y-129.0
X155.0Y-109.0
X155.0Y-129.0
T0
M30
