M48
; DRILL file {KiCad 8.0.2} date 2025-01-25T00:30:20-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-25T00:30:20-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X195.219Y-101.33
X196.235Y-106.41
X197.251Y-101.33
T2
X155.0Y-79.0
X196.0Y-112.0
M30
