M48
; DRILL file {KiCad 9.0.0} date 2025-04-17T11:42:54-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-17T11:42:54-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X130.75Y-129.95
T2
X82.5Y-96.0
X82.5Y-127.0
X129.5Y-96.0
X129.5Y-135.0
M30
