M48
; DRILL file {KiCad 7.0.8} date Sun Jan 21 00:30:29 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-21T00:30:29-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X136.5Y-65.9
X156.5Y-65.9
T2
X107.0Y-63.0
X107.0Y-129.0
X171.0Y-63.0
X171.0Y-129.0
T0
M30
