M48
; DRILL file {KiCad 9.0.0} date 2025-03-18T23:21:23-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-18T23:21:23-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1350
%
G90
G05
T1
X5.3051Y-3.6614
X5.315Y-5.0394
T2
X1.6791Y-4.3307
X2.1654Y-3.8106
X2.1654Y-4.8508
M30
