M48
; DRILL file {KiCad 9.0.0} date 2025-03-18T22:56:01-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-18T22:56:01-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X81.96Y-104.235
X87.04Y-103.219
X87.04Y-105.251
T2
X86.0Y-108.4
M30
