M48
; DRILL file {KiCad 9.0.0} date 2025-04-17T12:04:56-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-17T12:04:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.430
%
G90
G05
T1
X134.75Y-93.0
X135.0Y-128.0
T2
X42.65Y-110.0
X55.0Y-96.79
X55.0Y-123.21
M30
