M48
; DRILL file {KiCad 8.0.2} date 2025-02-01T19:12:36-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-01T19:12:36-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X107.62Y-97.934
X112.7Y-96.918
X112.7Y-98.95
T2
X87.0Y-85.0
X87.0Y-116.5
X112.0Y-85.0
X112.0Y-116.5
M30
